title: Donald White
#logo:
description: Aspiring data analyst with a newfound affinity for data and the numerous roles it play in our growing digital world. Learning key technical skills such as SQL, Python, Excel, and Tableau has allowed me to create numerous project to showcase them. 
My goal is to utilize these tools and other analytical techniques I have learned to contribute to a company that is searching for someone with my skillset.
show_downloads: true
theme: jekyll-theme-minimal
