title: Donald White
logo: /assets/portfolio-logo.jpg
description: Hello, I am as an aspiring data analyst that is proficient in analytical tools such as SQL, Python, Excel, and Tableau. I use data to drive business decisions and improve efficiency where it is needed. I look forward to making a positive within a team of analysts and grow in the field of data analytics.
show_downloads: true
theme: jekyll-theme-minimal
